# 00. Pytorch Fundamentals    
## Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [65]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

2.1.2+cu121


## introduction to tensors

### Creating tensors

#### pytorch tensors are created using 'torch.tensor()'

In [14]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [15]:
scalar.ndim

0

In [16]:
# Get tensor back as python int

scalar.item()

7

# Vector


In [17]:

vector = torch.tensor([7,7])

1

In [18]:
vector.ndim

1

In [19]:
vector.shape

torch.Size([2])

# Matrix


In [32]:

MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [33]:
MATRIX.ndim

2

In [34]:
MATRIX[0]

tensor([7, 8])

In [35]:
MATRIX.shape

torch.Size([2, 2])

# tensor

In [36]:

TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [37]:
TENSOR.ndim

3

In [38]:
TENSOR.shape

torch.Size([1, 3, 3])

# Random Tensors

### Why random tensors are important?
### because the way many neural networks learn is that
### they start with tensors full of random numbers
### and then adjust those random numbers
### to better represent the data

### start with random numbers -> look at data 
### -> update random numbers  -> look at data
### -> update random numbers

In [45]:
# create a random tensor of size(3,4)

random_tensor = torch.rand(1, 3,4)
random_tensor

tensor([[[0.0453, 0.0857, 0.9704, 0.4541],
         [0.9421, 0.4110, 0.0926, 0.1047],
         [0.4684, 0.6457, 0.8882, 0.6364]]])

In [46]:
random_tensor.ndim

3

In [47]:
random_tensor.shape

torch.Size([1, 3, 4])

# create a random tensor with similar shape to an image tensor

### height, width, number of color channels RGB

In [53]:

random_image_size_tensor = torch.rand(size=(224,224,3))

In [54]:
random_image_size_tensor

tensor([[[6.6246e-01, 7.6145e-01, 4.5105e-01],
         [7.9098e-02, 8.9949e-01, 7.2903e-01],
         [2.5651e-01, 5.1943e-01, 4.1376e-01],
         ...,
         [3.9056e-01, 9.3013e-01, 7.6522e-02],
         [3.4133e-01, 5.4784e-01, 6.4806e-01],
         [6.4371e-01, 9.4782e-02, 3.6684e-02]],

        [[7.3617e-01, 2.1992e-01, 6.1007e-01],
         [7.7685e-01, 9.1694e-01, 4.6254e-01],
         [2.4760e-01, 5.8392e-02, 5.7244e-01],
         ...,
         [4.2240e-01, 8.6157e-02, 8.6074e-02],
         [3.9452e-01, 1.1250e-01, 3.0502e-01],
         [8.8254e-01, 8.2531e-01, 7.6113e-01]],

        [[5.4145e-01, 7.2198e-01, 9.0374e-01],
         [8.1715e-01, 5.8029e-01, 6.8607e-01],
         [1.3420e-01, 3.2073e-01, 6.1109e-01],
         ...,
         [3.3283e-01, 6.2826e-01, 2.6579e-01],
         [6.6087e-01, 4.4121e-01, 1.0489e-01],
         [1.5790e-01, 5.8892e-01, 4.2023e-01]],

        ...,

        [[4.7189e-01, 2.1143e-01, 6.9529e-04],
         [6.0800e-01, 3.5320e-01, 8.9575e-01]

In [49]:
random_image_size_tensor.ndim

3

In [50]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [56]:
random_image_size_tensor2 = torch.rand(224,224,3)

In [57]:
random_image_size_tensor2

tensor([[[0.1240, 0.2234, 0.1734],
         [0.8295, 0.0709, 0.5530],
         [0.4113, 0.8017, 0.7595],
         ...,
         [0.0837, 0.9166, 0.4565],
         [0.9125, 0.8829, 0.0507],
         [0.6996, 0.1848, 0.0932]],

        [[0.7877, 0.3057, 0.2250],
         [0.7203, 0.0327, 0.0381],
         [0.4809, 0.4850, 0.6086],
         ...,
         [0.9007, 0.7279, 0.7286],
         [0.2892, 0.8970, 0.7805],
         [0.4281, 0.0897, 0.6700]],

        [[0.9662, 0.0340, 0.3292],
         [0.4376, 0.7191, 0.2174],
         [0.3618, 0.0445, 0.3943],
         ...,
         [0.6255, 0.7393, 0.6305],
         [0.7634, 0.5117, 0.4341],
         [0.3726, 0.4208, 0.9180]],

        ...,

        [[0.3198, 0.6075, 0.7710],
         [0.7696, 0.3766, 0.2362],
         [0.3458, 0.5616, 0.7820],
         ...,
         [0.0304, 0.8424, 0.7771],
         [0.6100, 0.3686, 0.1903],
         [0.8139, 0.6031, 0.5843]],

        [[0.3906, 0.7728, 0.6288],
         [0.7921, 0.9876, 0.9995],
         [0.

In [55]:
random_image_size_tensor2.shape

torch.Size([224, 224, 3])

# zeros and ones

In [ ]:

zero = torch.zeros(3,4)
zero

In [70]:
ones = torch.ones(3,4)
ones

ones.dtype

torch.float32

# Create a range of tensors and tensors-like

In [74]:
one_to_ten = torch.arange(0, 10)
one_to_ten

# creating tensors like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

# Tensor data types



In [84]:
# float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  #what datatype is the tensor float16,32,64, complex32,128 => percision computing
                               device="cpu", #or cuda
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [82]:
float_32_tensor.dtype

torch.float32

In [85]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [86]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [88]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)

In [89]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [90]:
float_32_tensor.dtype


device(type='cpu')

In [91]:
float_32_tensor.shape


torch.Size([3])

In [92]:
float_32_tensor.device

device(type='cpu')

# Manipulating Tensors (Tensor Operations)

- Addition
- Subtraction
- Multiplication
- Dvision
- Matrix Multiplication

### create a tensor & add 10 to it

In [93]:
tensor = torch.tensor([1,2,3])

In [94]:
tensor + 10

tensor([11, 12, 13])

### Multiply tensor by 10

In [96]:
tensor * 10

tensor([10, 20, 30])

### subtract 10

In [98]:
tensor - 10

tensor([-9, -8, -7])

In [102]:
# pytorch in-built functions
torch.mul(tensor, 10)
#torch.add()

tensor([10, 20, 30])

# Dot Matrix Multiplication

### 1) Inner Dimension must match (3,2).(2,3) ... 2 & 2

### 2) Output equal to shape of Outer Dimension (3,2).(2,3) ... 3 & 3

In [104]:
# Element Wise Multiplication
tensor * tensor

tensor([1, 4, 9])

In [105]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

## One of the most common errors in deep learning => shape error

In [109]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### To fix our tensor shape issues, we can manipulate the shape of one of our tensors using transpose
### A transpose switches the axes or dimensions of a given tensor

In [111]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

# Tensor aggregation (finding the min, max, mean, sum)

In [113]:
x = torch.arange(0,100,10)

In [118]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [119]:
x.dtype

torch.int64

In [115]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [116]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [124]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [126]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### finding the positional min "argmin" & max "argmax"

In [128]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [132]:
# find the position in tensor that has the min value with argmin -> returns index position where min value occurs
x.argmin()

tensor(0)

In [133]:
x.argmax()

tensor(9)

### Reshaping, stacking, squeezing, unsqueezing tensors

- reshaping => reshapes an input tensor to a defined shape
- view => return a view of an input tensor of certain shape but keep the same memory as the original tensor
- stacking => combine multiple tensors on top of each other (vstack) or side by side (hstack)
- squeeze => removes all '1' dim from a tensor
- unsqueeze => add a '1' dim to a target tensor
- premute => return a view of the input with dim permuted "swapped" in a certain way

In [150]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

### add an extra dim "reshape"
### - reshaping => reshapes an input tensor to a defined shape


In [151]:
x_reshaped = x.reshape(9) #same ... no change
x_reshaped = x.reshape(1,9) #adding []
x_reshaped = x.reshape(1,1,9) # adding two [[ ]]
x_reshaped

tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]])

### change the view "view"
### - view => return a view of an input tensor of certain shape but keep the same memory as the original tensor
#### changin z -> changes x (because a view of a tensor shares the same memory as the original input)

In [157]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [158]:
z = x.view(1,9)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [160]:
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

### stack tensors on top of each other

In [167]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

### torch.squeeze() - removes all single dimensions from a target tensor

In [169]:
x_reshaped

tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [170]:
x_reshaped.shape

torch.Size([1, 1, 9])

In [176]:
x_squeezed = x_reshaped.squeeze()

In [173]:
x_reshaped.squeeze().shape

torch.Size([9])

### torch unsqueeze() - adds a single dim to a target tensor at a specific dim

In [183]:
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [184]:
x_squeezed.shape

torch.Size([9])

In [181]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [182]:
x_unsqueezed.shape

torch.Size([1, 9])

### torch.permute - rearranges the dimensions of a target tensor in a specified order

In [188]:
x_original = torch.rand(size=(244,244,3)) #height, width, color channels
x_original.shape

torch.Size([244, 244, 3])

In [191]:
x_original.permute(2,0,1).shape #shifts axis 2->0 && 0->1 && 1->2

torch.Size([3, 244, 244])

### indexing -> selecting data from tensors
- indexing with pytorch is similar to indexing with numpy

In [194]:
import torch
x = torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [195]:
x.shape

torch.Size([9])

In [202]:
x = x.reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [200]:
x.shape

torch.Size([1, 3, 3])

In [207]:
x[0] #index our new tensor "dim=0"

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [208]:
x[0][0] #index the middle bracket "dim=1"

tensor([1, 2, 3])

In [209]:
x[0][0][0] #index the most inner bracket "last dimension"

tensor(1)

In [210]:
# you can also use ":" to select "all" of a target dimension

In [211]:
x[:,0]

tensor([[1, 2, 3]])

In [212]:
x[:,:,0]

tensor([[1, 4, 7]])

In [214]:
x[:,:,1] #gets all values of 0th and 1st dimension but only index 1 of 2nd dimension

tensor([[2, 5, 8]])

In [216]:
x[:, 1, 1] #gets all values of the 0 dim but only the 1 index value of 1st & 2nd dim

tensor([5])

In [217]:
#get index 0 of 0th and 1st dim and all values of 2nd dim
x[0,0,:]

tensor([1, 2, 3])

In [221]:
#index on x to return 9
x[0,2,2]

tensor([7, 8, 9])

In [219]:
#index on x to return 3,6,9

In [222]:
x[0,:,2]

tensor([3, 6, 9])

# pytorch tensors & numpy
### numpy is a popular scientific numerical computing library
- data in numpy, want in pytorch tensor -> `torch.from_numpy(ndarray))
- pytorch tensor -> numpy -> torch.Tensor.numpy()

# numpy array => tensor

In [226]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

### change the value of array, what will this do to tensor?
### no change to tensor!!

In [228]:
array = array + 1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

# tensor => numpy

In [230]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducability (trying to take random out of random)

- this is how neural network learns
- starts with random numbers
- => tensor operations
- => update random numbers to try
- => make them better representation of the data
- => again
- => again
- to reduce the randomness => random seed

In [239]:
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_a = torch.rand(3,4)
random_tensor_a


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [240]:
torch.manual_seed(RANDOM_SEED)
random_tensor_b = torch.rand(3,4)
random_tensor_b

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

# Running tensors & pytorch objects on GPUs => faster computations

### 1) Is GPU setup

In [242]:
!nvidia-smi

Mon Jun  3 12:55:44 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 537.13                 Driver Version: 537.13       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1060      WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   48C    P8               4W /  78W |    139MiB /  6144MiB |     11%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2 check gpu access with pytorch

In [243]:
import torch

torch.cuda.is_available()

True

### 3 setup device agnostic code

In [248]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

### 4 count number of devices

In [250]:
torch.cuda.device_count()

1

# Putting tensors & models on GPU
- the reason we want our tensors/models on the gpu because using gpu results in faster computations

### create tensor (default on the cpu)

In [252]:
tensor = torch.tensor([1,2,3], device="cpu")
tensor.device

device(type='cpu')

In [253]:
tensor = torch.tensor([1,2,3])
tensor.device

device(type='cpu')

### create tensor (on gpu)

In [257]:
tensor_on_gpu = tensor.to(device)
tensor.device

device(type='cuda', index=0)

In [258]:
tensor = torch.tensor([1,2,3], device="cuda")
tensor.device

device(type='cuda', index=0)

### moving tensors back to cpu
- if tensor on gpu => CAN NOT transform it to numpy

In [259]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [262]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)

In [ ]:
### exercuses & extra-curriculum